routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomsController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\CustomersController;
use App\Models\Booking;
use App\Models\Customers;
use App\Models\Rooms;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/









//  Users Routes
// Route::get('/users',[RegisterController::class,'index'])->name('users');
// Route::get('/user/create',[RegisterController::class,'addUser'])->name('user.create');
// Route::post('/user/create',[RegisterController::class,'store'])->name('user.store');
Auth::routes([
     'register' => true
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware'=>['auth']],function(){
    // Dashboard Route
    Route::get('/', function () {

    $rooms=Rooms::count();
    $customers=Customers::count();
    $bookings=Booking::count();
    return view('dashboard',compact('rooms','customers','bookings'));
});

    // Rooms Routes
    Route::resource('/rooms',RoomsController::class);
    Route::get('/room/delete/{id}',[RoomsController::class,'destroy'] )->name('rooms.destroy');

    //Customoers Routes
    Route::resource('/customers',CustomersController::class);
Route::get('/customers/delete/{id}',[CustomersController::class,'destroy'] )->name('customer.delete');

// Booking Routes
       Route::resource('/booking',BookingController::class);
// booking filtering Route
    Route::get('booking/available-rooms/{checkin_date}',[BookingController::class,'available_rooms']);

    // users Route
//    Route::get('/users',[RegisterController::class,'index'])->name('users');
});

app/Models/Customers.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    use HasFactory;
    protected $guarded=['id'];

    public function booking(){
        return $this->hasMany(Booking::class,'customer_id','id');
    }

    // public function setCreatedAtAttribute($value){
    //     return $this->attribute['created_ate']=Carbon::createFromDate('m/d/y',$value)->format('d/m/y');
    // }

    protected  $casts = [
        'created_at' => 'datetime:Y-m-d'
    ];


}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers=Customers::orderByDesc("customerName")->get();
        return view('Customers.index',compact('customers'));
    }
    public function allCustomers()
    {
     $customers=Customers::orderByDesc("customerName")->get();

     return response()->json([
        'customers'=>$customers
     ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('Customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $validate=Validator::make($request->all(),[
        //     'customerName'=>'required',
        //     'email'=>'required|email',
        //     'phone'=>'required',
        //     'city'=>'required',
        // ]);

        // if ($validate->fails()) {
        //     return response()->json([
        //         'status'=>400,
        //         'errors'=>$validate->messages()
        //     ]);
        // } else {
        //     Customers::create($request->all());
        //     return response()->json([
        //         'status'=>200,
        //         'message'=>'Customer Added Succesfully'
        //     ]);
        // }

         Customers::create($request->all());
         return redirect('/customers');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function show(Customers $customers)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function edit(Customers $customers,$id)
    {
        $customer=Customers::findOrFail($id);
        return view('Customers.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

         $customer=Customers::findOrFail($id);
         $customer->update($request->all());
        return redirect('/customers');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
           $customer=Customers::findOrFail($id);
           $customer->delete();
             return redirect('/customers');
    }
}

resources/views/Customers/create.blade.php
@extends('layouts')
@section('content')


    <div class="container  p-4">
        <form action="{{ route('customers.store') }}" method="POST">
            @csrf
            <div class="card border-left-primary text-dark  font-weight-bold ">
                <div class="   card-header">
                    <h3 class="text-dark font-weight-bold ">Add New Customer</h3>
                </div>

                <div class="row p-3 ">
                    <div class="col-6 text-dark">


                        <div class="form-group ">
                            <label class="form-label">Customer Name</label>
                            <input type="text" class="form-control" name="customerName">
                        </div>
                        <div class="form-group">

                            <label class="form-label">Phone</label>
                            <input type="text" class="form-control" name="phone">
                        </div>
                    </div>

                    <div class="col-6">

                        <div class="form-group">

                            <label class="form-label">Email</label>
                            <input type="text" class="form-control" name="email">
                        </div>

                        <div class="form-group">

                            <label class="form-label">City</label>
                            <input type="text" class="form-control" name="city">
                        </div>





                    </div>



                    <div class="form-group m-auto">

                        <button type="submit" class="btn btn-primary mt-4">Add New Customer</button>
                        <a href="/customers" type="button" class="btn btn-danger mt-4">Go back To Customers</a>
                    </div>




                </div>
        </form>
    </div>
    </div>


@endsection

resources/views/Customers/edit.blade.php
@extends('layouts')
@section('content')


    <div class="container  p-4">
        <form action="{{ route('customers.update', $customer->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card border-left-primary text-dark  font-weight-bold ">
                <div class="   card-header">
                    <h3 class="text-dark font-weight-bold ">Add New Customer</h3>
                </div>

                <div class="row p-3 ">
                    <div class="col-6 text-dark">


                        <div class="form-group ">
                            <label class="form-label">Customer Name</label>
                            <input type="text" class="form-control" name="customerName"
                                value="{{ $customer->customerName }}">
                        </div>
                        <div class="   form-group">

                            <label class="form-label">Phone</label>
                            <input type="text" class="form-control" name="phone" value="{{ $customer->phone }}">
                        </div>
                    </div>

                    <div class="col-6">

                        <div class="form-group">

                            <label class="form-label">Email</label>
                            <input type="text" class="form-control" name="email" value="{{ $customer->email }}">
                        </div>

                        <div class="form-group">

                            <label class="form-label">City</label>
                            <input type="text" class="form-control" name="city" value="{{ $customer->city }}">
                        </div>





                    </div>



                    <div class="form-group m-auto">

                        <button type="submit" class="btn btn-primary mt-4">Edit Customer info</button>
                        <a href="/customers" type="button" class="btn btn-danger mt-4">Go back To Customers</a>
                    </div>




                </div>
        </form>
    </div>
    </div>


@endsection

resources/views/Customers/index.blade.php
@extends('layouts')
@section('title')
    All Customers Info
@endsection

@section('css')
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection
@section('content')

    {{-- End- AddCustomerModal --}}
    <div class="container-fluid">
        <h4 class="successmessage"></h4>
        <div class="">
            <a href="{{ route('customers.create') }}" type="button" class="btn btn-primary ">
                Add New Customer
            </a>

            <div class="card shadow mt-4">
                <div class="card-header py-3">
                    <h2 class="m-0 font-weight-bold f text-dark">All Customers List</h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table  text-center font-weight-bold" id="dataTable">
                            <thead class="">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">
                                        <h5>Customer Name </h5>
                                    </th>
                                    <th scope="col">
                                        <h5>Email</h5>
                                    </th>
                                    <th scope="col">
                                        <h5>Country</h5>
                                    </th>
                                    <th scope="col">
                                        <h5>Phone</h5>
                                    </th>
                                    <th scope="col">
                                        <h5>Created Date</h5>
                                    </th>
                                    <th scope="col" class="not-export">
                                        <h5>Actions</h5>
                                    </th>


                                </tr>
                            </thead>
                            <tfoot class="">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Customer Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Country</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Created at</th>
                                    <th scope="col" class="not-export">Actions</th>


                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($customers as $customer)
                                    <tr>
                                        <td> {{ $loop->iteration }}</td>
                                        <td> {{ $customer->customerName ?? ' ' }}</td>

                                        <td>{{ $customer->email ?? ' ' }} </td>
                                        <td>{{ $customer->city ?? ' ' }} </td>
                                        <td>{{ $customer->phone ?? ' ' }} </td>
                                        <td>
                                            {{ $customer->created_at ?? '  2025' }}
                                            {{-- {{ \Carbon\Carbon::createFromTimestamp(strtotime($customer->created_at))->format('d-m-Y') ?? '2025 ' }} --}}
                                        </td>
                                        <td class="text-center">

                                            <a href="{{ route('customers.edit', $customer->id) }}"
                                                class="btn btn-circle btn-success"><i class="fas fa-edit"></i></a>
                                            <a href="{{ route('customer.delete', $customer->id) }}}" type="button"
                                                class="btn btn-circle btn-danger"><i class="fas fa-trash"></i></a>

                                        </td>


                                    </tr>

                                @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('script')
    {{-- <script>
        $(document).ready(function() {

            fetchAllCustomers();
            // fetching all customer inside table using ajax +jquery code
            function fetchAllCustomers() {
                $.ajax({
                    type: "GET",
                    url: "/allcustomers",

                    dataType: "json",
                    success: function(response) {

                        $('tbody').html(' ');
                        $.each(response.customers, function(key, customer_value) {
                            $('tbody').append(
                                '<tr>\
                                                                                                                                                        <td>' +
                                customer_value
                                .id +
                                '</td>\
                                                                                                                                                        <td>' +
                                customer_value
                                .customerName +
                                '</td>\
                                                                                                                                                        <td>' +
                                customer_value
                                .email +
                                '</td>\
                                                                                                                                                        <td>' +
                                customer_value
                                .phone +
                                '</td>\
                                                                                                                                                        <td>' +
                                customer_value
                                .city +
                                '</td>\
                                                                                                                                                        <td><button type="button" value="' +
                                customer_value
                                .id +
                                '" class="btn btn-info editbtn btn-sm">Edit</button><button type="button" value="' +
                                customer_value.id +
                                '" class="btn btn-danger deletebtn btn-sm">Delete</button></td>\
                                                                                                                                                        </tr>'
                            );
                        });
                    }
                });
            }


            // add customer using ajax + jquery code
            $('.add_customer').click(function(e) {
                e.preventDefault();
                var data = {
                    'customerName': $('.customerName').val(),
                    'email': $('.email').val(),
                    'phone': $('.phone').val(),
                    'city': $('.city').val(),

                }
                // csrfToken
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    type: "POST",
                    url: "/customers",
                    data: data,
                    dataType: "json",
                    success: function(response) {
                        if (response.status == 400) {
                            $('.customerErrors').html(' ');
                            $('.customerErrors').addClass('alert alert-danger text-white');
                            $.each(response.errors, function(key, error_value) {
                                $('.customerErrors').append('<li>' + error_value +
                                    '</li>');
                            });
                        } else {
                            $('.customerErrors').html(' ');
                            $('.successmessage').addClass('alert alert-success text-white');
                            $('.successmessage').text(response.message);
                            $('#AddCustomerModal').modal('hide');
                            $('#AddCustomerModal').find('input').val(' ');
                            fetchAllCustomers();

                        }
                    }
                });

            });
        });
    </script> --}}
    <!-- DataTable -->
    {{-- <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js" type="text/javascript"></script> --}}

    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js">
    </script>
    <script type="text/javascript" charset="utf8"
        src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js">
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js">
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js">
    </script>
    <script>
        jQuery(document).ready(function($) {
            $('#dataTable').DataTable({
                // dom: 'Bfrtip',
                dom: "Blfrtip",

                buttons: [{
                        extend: 'pdfHtml5',
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-file-pdf mr-1 "></i> PDF</button>',

                        title: 'All Customers List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }

                    },
                    {
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-file-csv mr-1"></i> CSV</button>',
                        extend: 'csvHtml5',
                        title: 'All Customers List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }
                    },
                    {
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-file-excel mr-1"></i> Excel</button>',
                        extend: 'excelHtml5',
                        title: 'All Customers List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }
                    },
                    {
                        extend: 'print',
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-print mr-1"></i> Print</button>',

                        pageSize: 'A4',
                        title: 'All Customers List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }

                    },
                ]
            });

        });
    </script>
@endsection