routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomsController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\CustomersController;
use App\Models\Booking;
use App\Models\Customers;
use App\Models\Rooms;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/









//  Users Routes
// Route::get('/users',[RegisterController::class,'index'])->name('users');
// Route::get('/user/create',[RegisterController::class,'addUser'])->name('user.create');
// Route::post('/user/create',[RegisterController::class,'store'])->name('user.store');
Auth::routes([
     'register' => true
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware'=>['auth']],function(){
    // Dashboard Route
    Route::get('/', function () {

    $rooms=Rooms::count();
    $customers=Customers::count();
    $bookings=Booking::count();
    return view('dashboard',compact('rooms','customers','bookings'));
});

    // Rooms Routes
    Route::resource('/rooms',RoomsController::class);
    Route::get('/room/delete/{id}',[RoomsController::class,'destroy'] )->name('rooms.destroy');

    //Customoers Routes
    Route::resource('/customers',CustomersController::class);
Route::get('/customers/delete/{id}',[CustomersController::class,'destroy'] )->name('customer.delete');

// Booking Routes
       Route::resource('/booking',BookingController::class);
// booking filtering Route
    Route::get('booking/available-rooms/{checkin_date}',[BookingController::class,'available_rooms']);

    // users Route
//    Route::get('/users',[RegisterController::class,'index'])->name('users');
});

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use HasFactory;
    protected $guarded=['id'];



    public function Customer(){
        return $this->belongsTo(Customers::class);
    }
    public function Room(){
        return $this->belongsTo(Rooms::class);
    }
     public function getStayingAttribute()
    {
        # code...
        return $this->checkin_date->diffInDays($this->checkout_date);
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use App\Models\Customers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\Rooms;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bookings=Booking::with('Customer','Room')->get();
        // dd($bookings);
        return view('Bookings.index',compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
          $customers=Customers::get();
        return view('Bookings.create',compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            Booking::create($request->all());
            return redirect('/booking');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $booking=Booking::findOrFail($id);

          $customers=Customers::get();
        return view('Bookings.edit',compact('booking','customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $booking=Booking::findOrFail($id);
         $booking->update($request->all());
        return redirect('/booking');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }

     function available_rooms(Request $request,$checkin_date){
        $arooms=DB::SELECT("SELECT * FROM rooms WHERE id NOT IN
        (SELECT room_id FROM bookings WHERE '$checkin_date' BETWEEN checkin_date AND checkout_date)");

        // $data[]=$arooms;
        // foreach($arooms as $room){
        //     $roomTypes=Rooms::find($room->id);
        //     $data[]=['room'=>$room,];
        // }

        return response()->json(['data'=>$arooms]);
    }
}

resources/views/Bookings/create.blade.php
@extends('layouts')
@section('content')




    <div class="container">
        <form action="{{ route('booking.store') }}" method="POST">
            @csrf
            <div class="card border-left-primary text-dark  font-weight-bold ">
                <div class="   card-header">
                    <h3 class="text-dark font-weight-bold ">Book A Room abdikani sugule</h3>
                </div>

                <div class="row p-3 ">
                    <div class="col-6 text-dark"">
                                                                                                            <div>
                                                                                                                <label for="
                        check in" class="form-label text-dark"">Choose Customer Name</label>
                                                                                                        <select class="






                                   form-control " name="customer_id">
                        <option>Choos Customer</option>
                        @foreach ($customers as $customer)

                            <option value="{{ $customer->id }}">{{ $customer->customerName }}</option>
                        @endforeach
                        </select>
                    </div>

                    <div class="">
                        <label for="check in" class="form-label my-3">Check out</label>
                        <input type="date" class="form-control" name="checkout_date">
                    </div>
                    {{-- <div>
                        <label for="check in" class="form-label my-3">Total Staying Days</label>
                        <input type="number" class="form-control  " name="staying_days">
                    </div> --}}

                </div>

                <div class="col-6">


                    <div>
                        <label for="check in" class="form-label">Check in</label>
                        <input type="date" class="form-control checkin-date" name="checkin_date">
                    </div>
                    <div class="">
                        <label for="total_adults" class="form-label my-3">Availabe Rooms</label>
                        <select class="form-control room-list" name="room_id">
                            <option selected>Availabe Rooms</option>
                        </select>
                    </div>


                    <div>
                        <label for="check in" class="form-label my-3">Total Persons</label>
                        <input type="number" class="form-control " name="total_adults">
                    </div>



                    <button type="submit" class="btn btn-primary mt-3 ">Book Rooms</button>
                </div>







            </div>
        </form>
    </div>
    </div>


@endsection





@section('script')


    {{-- <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script> --}}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $(".checkin-date").on('blur', function() {

                var _checkindate = $(this).val();
                console.log(_checkindate);
                // Ajax
                $.ajax({
                    url: "{{ url('booking') }}/available-rooms/" + _checkindate,
                    dataType: 'json',

                    // beforeSend: function() {
                    //     $(".room-list").append('<option>--- Loading ---</option>');
                    // },
                    success: function(res) {

                        console.log(res);
                        // var _html = '';
                        $.each(res.data, function(key, value) {


                            $(".room-list").append(
                                '<option value = ' + value.id + ' >' + "Room No-" +
                                value
                                .RoomName + '</option>'
                            );
                        });




                    }
                    // }
                });
            });
        });
    </script>
@endsection

resources/views/Bookings/edit.blade.php
@extends('layout')
@section('content')

    <div class="container">
        <form action="{{ route('booking.store', $booking->id) }}" method="POST">
            @csrf
            <div class="row p-3 ">
                <div class="col-5">
                    <div>
                        <label for="check in" class="form-label">Choose Customer Name</label>
                        <select class="form-select " name="customer_id">
                            <option>Choos Customer</option>
                            @foreach ($customers as $customer)

                                <option value="{{ $customer->id }}">{{ $customer->customerName }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="">
                        <label for="check in" class="form-label my-3">Check out</label>
                        <input type="date" class="form-control" name="checkout_date"
                            value="{{ $booking->checkout_date }}">
                    </div>
                    <div>
                        <label for="check in" class="form-label my-3">Total Staying Days</label>
                        <input type="text" class="form-control  " name="staying_days"
                            value="{{ $booking->staying_days }} " />
                    </div>

                </div>

                <div class="   col-5">


                    <div>
                        <label for="check in" class="form-label">Check in</label>
                        <input type="date" class="form-control checkin-date" name="checkin_date"
                            value="{{ $booking->checkin_date }}">
                    </div>
                    <div class="        ">
                        <label for="total_adults" class="form-label my-3">Availabe Rooms</label>
                        <select class="form-control room-list" name="room_id">
                            <option selected>Availabe Rooms</option>
                        </select>
                    </div>


                    <div>
                        <label for="check in" class="form-label my-3">Total Persons</label>
                        <input type="text" class="form-control " name="total_adults"
                            value="{{ $booking->total_adults }}">
                    </div>



                </div>






                <button type=" submit" class="btn btn-primary mt-3">Book it</button>

            </div>
        </form>

    </div>

@endsection





@section('script')


    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>


    <script type="text/javascript">
        $(document).ready(function() {

            $(".checkin-date").on('blur', function() {

                var _checkindate = $(this).val();
                console.log(_checkindate);
                // Ajax
                $.ajax({
                    url: "{{ url('booking') }}/available-rooms/" + _checkindate,
                    dataType: 'json',

                    // beforeSend: function() {
                    //     $(".room-list").append('<option>--- Loading ---</option>');
                    // },
                    success: function(res) {

                        console.log(res);
                        // var _html = '';
                        $.each(res.data, function(key, value) {


                            $(".room-list").append(
                                '<option value = ' + value.id + ' >' + "Room No-" +
                                value
                                .RoomName + '</option>'
                            );
                        });




                    }
                    // }
                });
            });
        });
    </script>
@endsection