routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomsController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\CustomersController;
use App\Models\Booking;
use App\Models\Customers;
use App\Models\Rooms;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/









//  Users Routes
// Route::get('/users',[RegisterController::class,'index'])->name('users');
// Route::get('/user/create',[RegisterController::class,'addUser'])->name('user.create');
// Route::post('/user/create',[RegisterController::class,'store'])->name('user.store');
Auth::routes([
     'register' => true
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware'=>['auth']],function(){
    // Dashboard Route
    Route::get('/', function () {

    $rooms=Rooms::count();
    $customers=Customers::count();
    $bookings=Booking::count();
    return view('dashboard',compact('rooms','customers','bookings'));
});

    // Rooms Routes
    Route::resource('/rooms',RoomsController::class);
    Route::get('/room/delete/{id}',[RoomsController::class,'destroy'] )->name('rooms.destroy');

    //Customoers Routes
    Route::resource('/customers',CustomersController::class);
Route::get('/customers/delete/{id}',[CustomersController::class,'destroy'] )->name('customer.delete');

// Booking Routes
       Route::resource('/booking',BookingController::class);
// booking filtering Route
    Route::get('booking/available-rooms/{checkin_date}',[BookingController::class,'available_rooms']);

    // users Route
//    Route::get('/users',[RegisterController::class,'index'])->name('users');
});

app/Models/Rooms.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rooms extends Model
{
    use HasFactory;
protected $guarded=['id'];

    public function booking(){
        return $this->hasMany(Booking::class,'room_id','id');
        // Carbon::()
    }
}

app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Rooms;
use Illuminate\Http\Request;


use Illuminate\Support\Facades\Validator;

class RoomsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $rooms=Rooms::get();
        return view('Rooms.Index',compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Rooms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $validate=Validator::make($request->all(),[
        //      'RoomName'=>'required',
        //     'Floor'=>'required',
        //     'Price'=>'required',
        // ]);
        // if ($validate->fails()) {
        //     return response()->json([
        //         'status'=>400,
        //          'errors'=>$validate->messages(),

        //     ]);
        // }else {

        //        return response()->json([
        //         'status'=>200,

        //          'message'=>"Room Added SuccessFully"

        //     ]);
        // }
         Rooms::create($request->all());
         return redirect('/rooms');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Rooms  $rooms
     * @return \Illuminate\Http\Response
     */
    public function show(Rooms $rooms)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Rooms  $rooms
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $room=Rooms::findOrFail($id);
        return view('Rooms.edit',compact('room'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Rooms  $rooms
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

            $room=Rooms::findOrFail($id);
                $room->update($request->all());

                return redirect('/rooms');




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Rooms  $rooms
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          $room=Rooms::findOrFail($id);
          $room->delete();
          return redirect('/rooms');
    }
}

resources/views/Rooms/Index.blade.php
@extends('layouts')
@section('title')
    All Rooms Info
@endsection
@section('css')
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection
@section('content')



    <div class="container-fluid">
        <h4 class="allmessages"></h4>


        <div class="card shadow mt-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-10">
                        <h2 class=" font-weight-bold font-size-5 text-dark">Rooms List</h2>

                    </div>
                    <div class="col-2">
                        <a href="{{ route('rooms.create') }}" type="button" class="btn btn-lg btn-primary ">
                            Add New Room
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table  text-center font-weight-bold" id="dataTable" width="100%">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">
                                    <h5>Room Name</h5>
                                </th>
                                <th scope="col">
                                    <h5>Floor</h5>
                                </th>
                                <th scope="col">
                                    <h5>Price</h5>
                                </th>
                                <th scope="col" class="text-center not-export">
                                    <h5>Actions</h5>
                                </th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Room Name</th>
                                <th scope="col">Floor</th>
                                <th scope="col">Price</th>
                                <th scope="col" class="text-center not-export">Actions</th>

                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach ($rooms as $room)
                                <tr>
                                    <td> {{ $loop->iteration }}</td>
                                    <td> {{ $room->RoomName ?? ' ' }}</td>

                                    <td>{{ $room->Price ?? ' ' }} $ </td>
                                    <td>{{ $room->Floor ?? ' ' }} Floor </td>
                                    <td class="text-center">

                                        <a href="{{ route('rooms.edit', $room->id) }}" type="button"
                                            class="btn btn-circle btn-success"><i class="fas fa-edit"></i></a>
                                        <a href="{{ route('rooms.destroy', $room->id) }}" type="button"
                                            class="btn btn-circle btn-danger"><i class="fas fa-trash"></i></a>


                                    </td>


                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
@endsection

@section('script')

    {{-- <script>
        $(document).ready(function() {
            fetchRooms();

            function fetchRooms() {
                $.ajax({
                    type: "GET",
                    url: "/fetchrooms",

                    dataType: "json",
                    success: function(response) {

                        $('tbody').html();
                        $.each(response.rooms, function(kay, item) {
                            $('tbody').append(
                                '<tr>\
                                                                                                                                                                                         <td>' +
                                item
                                .id +
                                '</td>\
                                                                                                                                                                                         <td>' +
                                item
                                .RoomName +
                                '</td>\
                                                                                                                                                                                          <td>' +
                                item
                                .Floor +
                                '</td>\
                                                                                                                                                                                          <td>' +
                                item
                                .Price +
                                " $" +
                                '</td>\
                                                                                                                                                                                          <td> <button   type="button" value="' +
                                item
                                .id +
                                '" class="btn btn-info  btn-sm editRoom">Edit</button><button type="button" value="' +
                                item.id +
                                '" class="btn btn-danger  btn-sm deleteRoom">Delete</button></td>\
                                                                                                                                                                     < /tr > '
                            );
                        });

                    }
                });
            }
            // ADDing rooms to database using ajax code
            $(document).on('click', '.add_room', function(e) {
                e.preventDefault();
                var data = {
                    'RoomName': $('.RoomName').val(),
                    'Floor': $('.Floor').val(),
                    'Price': $('.Price').val(),

                }

                // csrfToken
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                // Add New Room ajax code
                $.ajax({
                    type: "POST",
                    url: "/rooms",
                    data: data,
                    dataType: "json",
                    success: function(response) {
                        console.log(response);
                        if (response.status == 400) {
                            $('.roomErrors').html(' ');
                            $('.roomErrors').addClass("alert alert-danger text-white");
                            $.each(response.errors, function(key, err_value) {


                                $('.roomErrors').append('<li>' + err_value + '</li>');
                            });
                        } else {
                            $('.roomErrors').html(' ');
                            $('.allmessages').addClass('alert alert-success text-white');
                            $('.allmessages').text(response.message);
                            $('#AddRoomModal').modal('hide');
                            $('#AddRoomModal').find('input').val(' ');
                            fetchRooms();

                        }
                    }
                });
            });

            // Edit Room using ajax + jquery code

            $(document).on('click', '.editRoom', function(e) {
                e.preventDefault();
                var room_id = $(this).val();

                $('#editRoomModal').modal('show');

                $.ajax({
                    type: "GET",
                    url: "/edit-room/" + room_id,
                    data: "data",
                    dataType: "json",
                    success: function(response) {
                        if (response.status == 404) {

                            $('allmessages').html(' ');
                            $('allmessages').addClass('alert alter-danger');
                            $('allmessages').text(response.message);
                        } else {
                            $('.RoomName').val(response.room.RoomName);
                            $('.Floor').val(response.room.Floor);
                            $('.Price').val(response.room.Price);
                            $('#room_id').val(response.room.id);
                        }
                    }
                });
            });

            // Update Room code



            $(document).on('click', '.deleteRoom', function(e) {
                e.preventDefault();
                var room_id = $(this).val();

                $('#delete_room_id').val(room_id);

                $('#deleteRoomModal').modal('show');
            });
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(document).on('click', '.delete_room_btn', function(e) {
                e.preventDefault();
                var room_id = $('#delete_room_id').val();

                $.ajax({
                    type: "DELETE",
                    url: "/deleteroom/" + room_id,
                    dataType: "json",

                    success: function(response) {
                        console.log(response);

                        $('.allmessages').addClass('alert alert-danger');
                        $('.allmessages').text(response.message);
                        $('#deleteRoomModal').modal('hide');
                        fetchRooms();

                    }
                });
            });
        });
    </script> --}}

    {{-- Datatable cdns --}}
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js">
    </script>
    <script type="text/javascript" charset="utf8"
        src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js">
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js">
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js">
    </script>

    {{-- datatable code --}}
    <script>
        jQuery(document).ready(function($) {
            $('#dataTable').DataTable({
                // dom: 'Bfrtip',
                dom: "Blfrtip",

                buttons: [{
                        extend: 'pdfHtml5',
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-file-pdf mr-1 "></i> PDF</button>',

                        title: 'All Rooms List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }

                    },
                    {
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-copy mr-1"></i> Copy</button>',
                        extend: 'copyHtml5',
                        title: 'All Rooms List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }
                    },
                    {
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-file-excel mr-1"></i> Excel</button>',
                        extend: 'excelHtml5',
                        title: 'All Rooms List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }
                    },
                    {
                        extend: 'print',
                        text: '<button  class="btn  btn-primary w-100 px-3 "><i class="fa fa-print mr-1"></i> Print</button>',

                        pageSize: 'A4',
                        title: 'All Rooms List',
                        exportOptions: {
                            columns: ':visible:not(.not-export)'
                        }

                    },
                ]
            });

        });
    </script>
@endsection

resources/views/Rooms/create.blade.php
@extends('layouts')
@section('title')
    Add New Room
@endsection
@section('content')


    <div class="container  p-4">
        <form action="{{ route('rooms.store') }}" method="POST">
            @csrf
            <div class="card border-left-primary text-dark  font-weight-bold ">
                <div class="   card-header">
                    <h3 class="text-dark font-weight-bold ">Add New Room</h3>
                </div>

                <div class="row p-3 ">
                    <div class="col-6 text-dark">


                        <div class="form-group ">
                            <label class="form-label">Room Name</label>
                            <input type="text" class="form-control" name="RoomName">
                        </div>
                        <div class="form-group">

                            <label class="form-label">Floor</label>
                            <input type="text" class="form-control" name="Floor">
                        </div>
                    </div>

                    <div class="col-6">

                        <div class="form-group">

                            <label class="form-label">Price</label>
                            <input type="text" class="form-control" name="Price">
                        </div>







                    </div>



                    <div class="form-group m-auto">

                        <button type="submit" class="btn btn-primary mt-4">Add New Customer</button>
                        <a href="/rooms" type="button" class="btn btn-danger mt-4">Go back To Customers</a>
                    </div>




                </div>
        </form>
    </div>
    </div>


@endsection

resources/views/Rooms/edit.blade.php
@extends('layouts')
@section('title')
    Edit Room Info
@endsection
@section('content')


    <div class="container  p-4">
        <form action="{{ route('rooms.update', $room->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card border-left-primary text-dark  font-weight-bold ">
                <div class="   card-header">
                    <h3 class="text-dark font-weight-bold ">Edit Room Info</h3>
                </div>

                <div class="row p-3 ">
                    <div class="col-6 text-dark">


                        <div class="form-group ">
                            <label class="form-label">Room Name</label>
                            <input type="text" class="form-control" name="RoomName" value="{{ $room->RoomName }}">
                        </div>
                        <div class="   form-group">

                            <label class="form-label">Floor</label>
                            <input type="text" class="form-control" name="Floor" value="{{ $room->Floor }}">
                        </div>
                    </div>

                    <div class="   col-6">

                        <div class="form-group">

                            <label class="form-label">Price</label>
                            <input type="text" class="form-control" name="Price" value="{{ $room->Price }}">
                        </div>







                    </div>



                    <div class="   form-group m-auto">

                        <button type="submit" class="btn btn-primary mt-4">Edit Room Info</button>
                        <a href="/rooms" type="button" class="btn btn-danger mt-4">Go back To Customers</a>
                    </div>




                </div>
        </form>
    </div>
    </div>


@endsection